spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coinvest
    username: coinvest
    password: password

  redis:
    host: localhost
    port: 6379

jwt:
  secret: local_development_secret_key_random_string_at_least_64_chars_long_!!_secure_1234567890

app:
  security:
    aes-key: "12345678901234567890123456789012"
